name: Build Executable

on:
  push:
    tags:
      - 'b*'  # Disparar quando uma tag de versão for criada

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Generate Executable
        run: |
          pyinstaller --onefile --name=SNC-Query-Tool-${{ github.ref_name }} main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SNC-Query-Tool-${{ github.ref_name }}
          path: dist/