name: Publish Package

on:
  push:
    tags:
      - 'v*'  # Aciona quando há push em tags
  workflow_dispatch:  # Permite acionar o fluxo manualmente

jobs:
  build-and-version:
    if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/dev') || startsWith(github.ref, 'refs/heads/main')
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Clean previous builds
        run: |
          Remove-Item -Recurse -Force build -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force dist -ErrorAction SilentlyContinue

      - name: Generate Executable
        run: |
          pyinstaller --onefile --name=DeepSeek-Tool-${{ github.ref_name }} --clean main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DeepSeek-Tool-${{ github.ref_name }}
          path: dist/